import { Func } from '@prisma/client'
import axios from 'axios'
import Head from 'next/head'
import useSWR from 'swr'
import FuncCatalog from '../components/func-catalog'
import FuncEditor from '../components/func-editor'
import { getAllFuncs } from '../src/services/func'
import styles from '../styles/Home.module.css'

async function getFuncs(url): Promise<Func[]> {
  console.log(`Getting url: ${url}`)
  return (await axios.get<Func[]>(url)).data
}

export async function getStaticProps() {
  const initialFuncs = await getAllFuncs({})
  return { props: { initialFuncs } }
}

export default function Home({ initialFuncs }: { initialFuncs: Func[] }) {
  const { data: funcs } = useSWR('/api/funcs', getFuncs, { initialData: initialFuncs })

  return (
    <div className={styles.container}>
      <Head>
        <title>Lightning Bug</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Lightning Bug
        </h1>

        <FuncEditor />
        <FuncCatalog funcs={funcs} />

      </main>

      <footer className={styles.footer}>
      </footer>
    </div >
  )
}
